(require 'ert)
(require 'deep-ffn)

(ert-deftest test-deep-ffn-structure ()
  "Test the structure of the deep feedforward network."
  (let ((network (create-deep-ffn)))
    (should (= (length network) 4))
    (should (= (length (nth 0 (nth 0 network))) 10))
    (should (= (length (nth 1 (nth 0 network))) 20))
    (should (= (length (nth 0 (nth 1 network))) 20))
    (should (= (length (nth 1 (nth 1 network))) 15))
    (should (= (length (nth 0 (nth 2 network))) 15))
    (should (= (length (nth 1 (nth 2 network))) 10))
    (should (= (length (nth 0 (nth 3 network))) 10))
    (should (= (length (nth 1 (nth 3 network))) 5))
    (should (eq (nth 2 (nth 0 network)) 'ops-relu))
    (should (eq (nth 2 (nth 1 network)) 'ops-relu))
    (should (eq (nth 2 (nth 2 network)) 'ops-relu))
    (should (eq (nth 2 (nth 3 network)) 'identity))))

(provide 'deep-ffn-test)
